version: '3.8'
services:
  backend:
    container_name: fastapi-app
    
    build: .
    
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    
    volumes:
      - .:/app
    
    ports:
      - "8000:8000"
    
    environment:
      - MONGODB_URL=mongodb://db:27017/inventory-mng-local
    
    depends_on:
      - db
    
    networks:
      - app-network

  db:
    container_name: mobgodb
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=inventory-mng-local # MongoDB will create this database on first run
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
